# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83c4c70e0bd6c81226b5188338a831d862b89bd3b734f3cf312cf54ee4f79d6ee6c24d746e416b8ab40bf8c4e783fb332821700eaf1ee6f8f3edb8168e1cb556

test:
  secret_key_base: ef51460644f2adca1128de59218ccfe6de0288ed5b7a04ca0fb249a278ad2467d60b3be0d1ac36d65b1da985b1dcf297cd28e2368cdd41f90b13b3d966d75bee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
